site_name: HiWa House
#site_url: https://github.com/hiwa-house/teletraan

theme:
    name: material
    custom_dir: overrides
    icon:
#        logo: material/monitor-dashboard
        logo: solid-house-chimney
        admonition:
            gas-pump: fontawesome/solid/gas-pump
    favicon: solid-house-chimney.svg
#    favicon: apple-touch-icon.png
    features:
        - navigation.expand
        - navigation.instant
        - navigation.path
    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          primary: green
          toggle:
            icon: material/brightness-auto
            name: Switch to light mode
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          primary: green
          scheme: default 
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          primary: green
          scheme: slate
          toggle:
            icon: material/brightness-2
            name: Switch to system preference

extra_javascript:
    - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
    - javascripts/tablesort.js

markdown_extensions:
    # Python Markdown
    - admonition
    - attr_list
    - def_list
    - md_in_html
    - meta
    - tables
    - toc:
        permalink: true

    # Python Markdown Extensions
    - pymdownx.details
    - pymdownx.highlight
    - pymdownx.magiclink:
        hide_protocol: true
    - pymdownx.smartsymbols
    - pymdownx.snippets:
        url_download: true
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        clickable_checkbox: true

plugins:
    - awesome-pages:
        collapse_single_pages: true
    - search
    - table-reader:
        data_path: "docs"
